build:
  engine: hugo
  fetch_submodules: true

paths:
  static: static
  uploads: static/uploads

collections_config:
  pages:
    path: ''
    icon: wysiwyg

_structures:
  content_blocks:
    style: modal
    values:
      - label: Hero
        value:
          _bookshop_name: hero
          heading:
          subheading:
          image:
      - label: Cards
        value:
          _bookshop_name: cards
          heading:
          subheading:
          items:
            - title:
              text:
          postscript:

_inputs:
  content_blocks:
    type: array
  heading:
    type: text
  subheading:
    type: textarea
  image:
    type: image
  items:
    type: array
  postscript:
    type: text
